import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import React from "react";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <link rel="icon" href="favico.png" type="image/png"/>
            <title>Zsombor Pócs Portfolio</title>
        </head>
        <body className={inter.className}>
        <Navbar/>
        <main>{children}</main>
        </body>
        </html>
    );
}
